/***** DO NOT EDIT THIS FILE *****/
// Sample_android.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var Sample_android = {};

/*** script -- android ***/
Sample_android.android = function(app) {
	MT.Script.call(this, app, "android.mt");
};

Sample_android.android.prototype = new MT.Script;

Sample_android.android.prototype.call = function() {
	//run: android.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.android = function() {
	return new Sample_android.android(this);
};

